#page title
Progetto PoLive                               :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : it                                       # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :  https://teocavaa.github.io                              # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :  https://www.figma.com/file/DAz4no1XOLINWNiegq30Qk/booo?type=design&node-id=0%3A1&mode=design&t=670M4kiKRDsLjf1R-1                                        # Enter Google Play Store URL.
presskit_download_link                    : https://teocavaa.github.io                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/Polive.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : PoLive                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Applicazione per gli eventi.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Matteo Cavalleri                                
your_link                                 : https://teocavaa.github.io                    
your_city                                 : Como                             
email_address                             : mattecava02@gmail.com
facebook_username                         :                                           
instagram_username                        : _teocavaa_
twitter_username                          : 
github_username                           : teocavaa
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Informazioni preliminari
    description                           : Progetto per il corso di "Fondamenti di Human Computer Interaction" del Politecnico di Milano.                                   Progetto sviluppato dal gruppo BitEvent
    fontawesome_icon_name                 : cog
    
  - title                                 : Team
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : briefcase

  - title                                 : Brainstorming
    description                           : Abbiamo raccolto le esigenze delle persone del Politecnico e le abbiamo categorizzate in base all'importanza.
    fontawesome_icon_name                 : cloud

  - title                                 : Tasks
    description                           : Ricerca degli eventi. Espressione di giudizio. Pubblicazione eventi.
    fontawesome_icon_name                 : bolt
  
  - title                                 : Feature List
    description                           : Aggiungere le feature una ad una
    fontawesome_icon_name                 : star

  - title                                 : Feedback attivo
    description                           : Viene mostrato in modo intuitivo la sezione in cui mi trovo o l'operazione che sto compiendo.
    fontawesome_icon_name                 : eye-slash

  - title                                 : UI intuitiva
    description                           : Mostriamo un display facile e intuitivo anche per chi non ha confidenza con applicazioni mobile. Il nostro design ispirato a "Spotify" permette di apprendere le funzionalità offerte in maniera efficace e rapida.
    fontawesome_icon_name                 : fighter-jet

  - title                                 : Ricerca
    description                           : Utilizziamo una barra di ricerca con suggerimenti offerti da un algoritmo che permette di trovare velocemente eventi di tuo gradimento o cercati precedentemente. Inoltre è possibile utilizzare dei filtri per rendere la ricerca ancora più precisa.
    fontawesome_icon_name                 : filter

  - title                                 : Area utente
    description                           : Abbiamo una sezione dedicata all'utente completa e facile anche per chi è più inesperto. Per gli organizzatori sono previste funzioni aggiuntive in merito alla creazione e gestione di eventi.
    fontawesome_icon_name                 : cloud-upload

  - title                                 : Social Links
    description                           : Aggiungere social
    fontawesome_icon_name                 : link

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
